from datetime import datetime, timezone
from pydantic import BaseModel, Field
from typing import Optional, Union
import uuid

import logging
log = logging.getLogger(__name__)

class APRSMessage(BaseModel):
    """Model for LoRa message."""
    message_id: Optional[uuid.UUID] = Field(None, description="Message ID, new for each message to prevent duplicates. This is generated by the APRS receiver if it is not included in the raw data.")
    sender: Optional[str] = Field(None, description="ID of device that relayed message to us. Defaults to IP address for HTTP events, client ID for MQTT events, and nothing for APRS events.")
    raw_data: Union[dict, str, bytes] = Field(..., description="Raw APRS message. This is the raw data received from the APRS receiver.")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp of the message. Should be as close to the original timestamp as possible. If not included, the server will use the time of endpoint reception.")