// Package direwolf generates direwolf.conf from ground station config.
package direwolf

import (
	"fmt"
	"log/slog"
	"os"
	"text/template"

	"github.com/EricAndrechek/umich-balloons/ground-station/umbgs/internal/config"
)

const confPath = "/etc/direwolf.conf"

const confTemplate = `# Direwolf configuration - auto-generated by umbgs
# Do not edit manually; changes will be overwritten.

ACHANNELS 1
# Audio comes from rtl_fm piped to direwolf stdin via the "-" flag.
# ADEVICE null null tells direwolf not to open any ALSA/PulseAudio devices.
ADEVICE null null

GPSD

CHANNEL 0

MYCALL {{.Callsign}}

MODEM 1200
AGWPORT 8000
KISSPORT 8001
{{- if .IGServer}}

# APRS-IS iGate
IGSERVER {{.IGServer}}
IGLOGIN {{.Callsign}} {{.Passcode}}

# iGate TX limits: 6 packets in 30 sec, 10 packets in 60 sec
IGTXLIMIT 6 10

# Text beacon to APRS-IS
TBEACON SENDTO=IG DELAY=0:30 EVERY=1 SYMBOL=R& comment="{{.Comment}}"

# Position beacon to APRS-IS (car symbol with R overlay)
PBEACON SENDTO=IG DELAY=0:30 EVERY=1 SYMBOL="car" OVERLAY=R lat={{printf "%.7f" .Lat}} long={{printf "%.7f" .Lon}} alt={{.Alt}} comment="{{.Comment}}"
{{- end}}
`

// GenerateConfig writes direwolf.conf based on current config.
func GenerateConfig(cfg *config.Manager, logger *slog.Logger) error {
	c := cfg.Get()
	log := logger.With("service", "direwolf")

	tmpl, err := template.New("direwolf").Parse(confTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	callsign := c.UploaderCallsign()
	passcode := APRSISPasscode(c.Callsign)

	comment := c.APRS.BeaconComment
	if comment == "" {
		comment = "UMich Balloons Ground Station"
	}

	data := struct {
		Callsign string
		Passcode int
		IGServer string
		Comment  string
		Lat      float64
		Lon      float64
		Alt      int
	}{
		Callsign: callsign,
		Passcode: passcode,
		IGServer: c.APRS.IGServer,
		Comment:  comment,
		Lat:      c.APRS.BeaconLat,
		Lon:      c.APRS.BeaconLon,
		Alt:      c.APRS.BeaconAlt,
	}

	f, err := os.Create(confPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", confPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	log.Info("direwolf.conf generated", "callsign", data.Callsign, "igserver", data.IGServer, "passcode", data.Passcode)
	return nil
}
