// Package direwolf generates direwolf.conf from ground station config.
package direwolf

import (
	"fmt"
	"log/slog"
	"os"
	"strings"
	"text/template"

	"github.com/EricAndrechek/umich-balloons/ground-station/umbgs/internal/config"
)

const confPath = "/etc/direwolf.conf"

const confTemplate = `# Direwolf configuration - auto-generated by umbgs
# Do not edit manually; changes will be overwritten.

ACHANNELS 1
# Audio comes from rtl_fm piped to direwolf stdin via the "-" flag.
ADEVICE stdin null

CHANNEL 0

MYCALL {{.Callsign}}

MODEM 1200
AGWPORT 8000
KISSPORT 8001

# Read live position from gpsd (ground station is mobile).
# dwgpsd will log "timeout waiting for GPS data" until the GPS gets a fix — expected indoors.
GPSD
{{- if .IGServer}}

# APRS-IS iGate
IGSERVER {{.IGServer}}
IGLOGIN {{.Callsign}} {{.Passcode}}

# Block all inbound traffic from APRS-IS. We connect to the IS network
# purely to publish our own TBEACON below — we don't want to ingest the
# firehose of internet packets because it clutters direwolf's log and
# isn't relevant to local RF operations. "p/N0CALL" is a server-side
# prefix filter matching callsigns that start with "N0CALL", which is
# effectively no real station. Direwolf prints a warning at startup
# that IGFILTER is an "expert level feature" — that's expected, ignore.
IGFILTER p/N0CALL

# iGate TX limits: rate limit for RF retransmission of IS traffic.
# We're RX-only (no transmitter), so this is inert, but direwolf wants it set.
IGTXLIMIT 6 10

# Tracker beacon to APRS-IS every 2 minutes using live gpsd position
# (car symbol with R overlay). Standard mobile APRS rate; gives aprs.fi
# enough points to draw a continuous chase-vehicle trail while staying
# within APRS-IS etiquette. TBEACON pulls lat/lon from GPSD at transmit
# time; PBEACON requires a fixed lat/lon at config-parse time so we
# can't use it here. DELAY=0:30 = 30 seconds before first beacon.
TBEACON SENDTO=IG DELAY=0:30 EVERY=2 SYMBOL="car" OVERLAY=R comment="{{.Comment}}"
{{- end}}
`

// renderConfig returns the rendered direwolf.conf as a string. Extracted
// from GenerateConfig so it can be unit-tested without writing /etc.
func renderConfig(c config.Config) (string, error) {
	tmpl, err := template.New("direwolf").Parse(confTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	comment := c.APRS.BeaconComment
	if comment == "" {
		comment = "UMich Balloons Ground Station"
	}

	data := struct {
		Callsign string
		Passcode int
		IGServer string
		Comment  string
	}{
		Callsign: c.UploaderCallsign(),
		Passcode: APRSISPasscode(c.Callsign),
		IGServer: c.APRS.IGServer,
		Comment:  comment,
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return buf.String(), nil
}

// GenerateConfig writes direwolf.conf based on current config.
func GenerateConfig(cfg *config.Manager, logger *slog.Logger) error {
	c := cfg.Get()
	log := logger.With("service", "direwolf")

	out, err := renderConfig(c)
	if err != nil {
		return err
	}

	if err := os.WriteFile(confPath, []byte(out), 0644); err != nil {
		return fmt.Errorf("write %s: %w", confPath, err)
	}

	log.Info("direwolf.conf generated",
		"callsign", c.UploaderCallsign(),
		"igserver", c.APRS.IGServer,
		"passcode", APRSISPasscode(c.Callsign))
	return nil
}
