// Package direwolf generates direwolf.conf from ground station config.
package direwolf

import (
	"fmt"
	"log/slog"
	"os"
	"text/template"

	"github.com/EricAndrechek/umich-balloons/ground-station/umbgs/internal/config"
)

const confPath = "/etc/direwolf.conf"

const confTemplate = `# Direwolf configuration - auto-generated by umbgs
# Do not edit manually; changes will be overwritten.

ADEVICE plughw:0,0
ACHANNELS 1
CHANNEL 0

MYCALL {{.Callsign}}

MODEM 1200
FIX_BITS 1

AGWPORT 0
KISSPORT 8001

FREQ {{printf "%.3f" .Frequency}}
`

// GenerateConfig writes direwolf.conf based on current config.
func GenerateConfig(cfg *config.Manager, logger *slog.Logger) error {
	c := cfg.Get()
	log := logger.With("service", "direwolf")

	tmpl, err := template.New("direwolf").Parse(confTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	data := struct {
		Callsign  string
		Frequency float64
	}{
		Callsign:  c.UploaderCallsign(),
		Frequency: c.APRS.Frequency,
	}

	f, err := os.Create(confPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", confPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	log.Info("direwolf.conf generated", "callsign", data.Callsign, "freq", data.Frequency)
	return nil
}
