create table public.payloads (

  id bigint generated by default as identity not null,

  name text not null default ''::text,

  aprs_callsign text null,

  iridium_imei text null,

  constraint payloads_pkey primary key (id),

  constraint payloads_aprs_callsign_key unique (aprs_callsign),

  constraint payloads_id_key unique (id),

  constraint payloads_iridium_imei_key unique (iridium_imei)

) TABLESPACE pg_default;



create table public.raw_messages (

  id bigint generated by default as identity not null,

  server_received_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),

  source text not null,

  payload_id bigint not null,

  raw_data text not null,

  data_time timestamp with time zone null,

  source_id text null,

  constraint raw_messages_pkey primary key (id),

  constraint raw_messages_id_key unique (id),

  constraint raw_messages_payload_id_fkey foreign KEY (payload_id) references payloads (id) on update CASCADE on delete CASCADE

) TABLESPACE pg_default;

create table public.telemetry (

  id uuid not null default gen_random_uuid (),

  sources text[] not null,

  altitude double precision null,

  speed double precision null,

  heading double precision null,

  battery double precision null,

  extra jsonb null default '{}'::jsonb,

  last_updated timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),

  received_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),

  position geography not null,

  payload_id bigint not null,

  constraint telemetry_pkey primary key (id),

  constraint telemetry_payload_id_fkey foreign KEY (payload_id) references payloads (id) on update CASCADE on delete CASCADE

) TABLESPACE pg_default;